export const MONOPOLY_BOARD = [
  { id: 0, name: 'BẮT ĐẦU', type: 'start', description: 'Nhận $200 khi đi qua' },
  { id: 1, name: 'Đường Láng', type: 'property', color: '#8b4513', price: 60, rent: 2 },
  { id: 2, name: 'Khí Vận', type: 'chest' },
  { id: 3, name: 'Đường Bưởi', type: 'property', color: '#8b4513', price: 60, rent: 4 },
  { id: 4, name: 'Thuế Thu Nhập', type: 'tax', price: 200 },
  { id: 5, name: 'Bến xe Miền Đông', type: 'railroad', price: 200, rent: 25 },
  { id: 6, name: 'Phố Cổ', type: 'property', color: '#87ceeb', price: 100, rent: 6 },
  { id: 7, name: 'Cơ Hội', type: 'chance' },
  { id: 8, name: 'Hồ Gươm', type: 'property', color: '#87ceeb', price: 100, rent: 6 },
  { id: 9, name: 'Chợ Đồng Xuân', type: 'property', color: '#87ceeb', price: 120, rent: 8 },
  { id: 10, name: 'VÀO TÙ / THĂM TÙ', type: 'jail' },
  { id: 11, name: 'Chợ Bến Thành', type: 'property', color: '#ff1493', price: 140, rent: 10 },
  { id: 12, name: 'Công ty Điện Lực', type: 'utility', price: 150 },
  { id: 13, name: 'Đường Nguyễn Huệ', type: 'property', color: '#ff1493', price: 140, rent: 10 },
  { id: 14, name: 'Phố đi bộ', type: 'property', color: '#ff1493', price: 160, rent: 12 },
  { id: 15, name: 'Bến xe Mỹ Đình', type: 'railroad', price: 200, rent: 25 },
  { id: 16, name: 'Cầu Rồng', type: 'property', color: '#ffa500', price: 180, rent: 14 },
  { id: 17, name: 'Khí Vận', type: 'chest' },
  { id: 18, name: 'Bà Nà Hills', type: 'property', color: '#ffa500', price: 180, rent: 14 },
  { id: 19, name: 'Hội An', type: 'property', color: '#ffa500', price: 200, rent: 16 },
  { id: 20, name: 'BÃI ĐỖ XE', type: 'parking' },
  { id: 21, name: 'Vịnh Hạ Long', type: 'property', color: '#ff0000', price: 220, rent: 18 },
  { id: 22, name: 'Cơ Hội', type: 'chance' },
  { id: 23, name: 'Cát Bà', type: 'property', color: '#ff0000', price: 220, rent: 18 },
  { id: 24, name: 'Sapa', type: 'property', color: '#ff0000', price: 240, rent: 20 },
  { id: 25, name: 'Bến xe Nước Ngầm', type: 'railroad', price: 200, rent: 25 },
  { id: 26, name: 'Đà Lạt', type: 'property', color: '#ffff00', price: 260, rent: 22 },
  { id: 27, name: 'Hồ Tuyền Lâm', type: 'property', color: '#ffff00', price: 260, rent: 22 },
  { id: 28, name: 'Công ty Cấp Nước', type: 'utility', price: 150 },
  { id: 29, name: 'Nha Trang', type: 'property', color: '#ffff00', price: 280, rent: 24 },
  { id: 30, name: 'ĐI TÙ!', type: 'go_to_jail' },
  { id: 31, name: 'Phú Quốc', type: 'property', color: '#008000', price: 300, rent: 26 },
  { id: 32, name: 'Côn Đảo', type: 'property', color: '#008000', price: 300, rent: 26 },
  { id: 33, name: 'Khí Vận', type: 'chest' },
  { id: 34, name: 'Vũng Tàu', type: 'property', color: '#008000', price: 320, rent: 28 },
  { id: 35, name: 'Bến xe Giáp Bát', type: 'railroad', price: 200, rent: 25 },
  { id: 36, name: 'Cơ Hội', type: 'chance' },
  { id: 37, name: 'Landmark 81', type: 'property', color: '#0000ff', price: 350, rent: 35 },
  { id: 38, name: 'Thuế Xa Xỉ', type: 'tax', price: 100 },
  { id: 39, name: 'Bitexco', type: 'property', color: '#0000ff', price: 400, rent: 50 }
];

export const CHANCE_CARDS = [
  { text: 'Tiến đến ô BẮT ĐẦU (Nhận $200)', action: 'advance', to: 0 },
  { text: 'Tiến đến Phố Cổ', action: 'advance', to: 6 },
  { text: 'Tiến đến Vịnh Hạ Long', action: 'advance', to: 21 },
  { text: 'Tiến đến bến xe gần nhất', action: 'advance_railroad' },
  { text: 'Tiến đến công ty dịch vụ gần nhất', action: 'advance_utility' },
  { text: 'Ngân hàng trả lãi suất. Nhận $50', action: 'pay', amount: 50 },
  { text: 'Ra tù miễn phí. (Giữ thẻ này để dùng)', action: 'get_out_of_jail' },
  { text: 'Lùi lại 3 ô', action: 'move', amount: -3 },
  { text: 'ĐI TÙ! Đi thẳng vào tù, không nhận $200 nếu đi qua Bắt đầu', action: 'goto_jail' },
  { text: 'Sửa chữa nhà cửa. Trả $25 mỗi mảnh đất', action: 'property_repair', amount: 25 },
  { text: 'Đóng phạt giao thông $15', action: 'pay', amount: -15 },
  { text: 'Chuyến đi tới Bến xe Giáp Bát', action: 'advance', to: 35 },
  { text: 'Tiến đến Landmark 81', action: 'advance', to: 37 },
  { text: 'Được bầu làm Chủ tịch hội đồng quản trị. Trả mỗi người chơi $50', action: 'pay_players', amount: 50 },
  { text: 'Đầu tư sinh lời, nhận $150', action: 'pay', amount: 150 }
];

export const CHEST_CARDS = [
  { text: 'Tiến đến ô BẮT ĐẦU (Nhận $200)', action: 'advance', to: 0 },
  { text: 'Lỗi ngân hàng có lợi cho bạn. Nhận $200', action: 'pay', amount: 200 },
  { text: 'Trợ cấp y tế. Trả $50', action: 'pay', amount: -50 },
  { text: 'Nhận lại tiền thuế. Thu $20', action: 'pay', amount: 20 },
  { text: 'Ra tù miễn phí. (Giữ thẻ này để dùng)', action: 'get_out_of_jail' },
  { text: 'ĐI TÙ! Đi thẳng vào tù, không nhận $200 nếu đi qua Bắt đầu', action: 'goto_jail' },
  { text: 'Nhận tiền quỹ học bổng $50', action: 'pay', amount: 50 },
  { text: 'Quỹ kỳ nghỉ trưởng thành. Nhận $100', action: 'pay', amount: 100 },
  { text: 'Sinh nhật bạn! Nhận $10 từ mỗi người chơi', action: 'collect_players', amount: 10 },
  { text: 'Đóng phí bảo hiểm nhân thọ $100', action: 'pay', amount: -100 },
  { text: 'Chi phí bệnh viện $100', action: 'pay', amount: -100 },
  { text: 'Học phí $50', action: 'pay', amount: -50 },
  { text: 'Nhận $25 tiền dịch vụ tư vấn', action: 'pay', amount: 25 },
  { text: 'Bị đánh giá thuế đường. Trả $40 mỗi mảnh đất', action: 'property_repair', amount: 40 },
  { text: 'Bạn đã chiến thắng giải nhì cuộc thi sắc đẹp. Nhận $10', action: 'pay', amount: 10 },
  { text: 'Thừa kế $100', action: 'pay', amount: 100 }
];
